[project]
name = "catan-ai"
version = "0.1.0"

readme = "README.md"

requires-python = ">=3.11"
dependencies = ["pre_commit==4.1.0", "ruff==0.11.0"]

[lint]
select = [
    "E", # pycodestyle
    "F", # pyflakes
    "I", # isort
]
